# Creating the Dataset for 2014

This Notebook: 
 - Reads in our All Public Schools data for 2014
 - Creates a new column for low performing schools 
 - Cleans up the dataset for ML capabilities

In [2]:
#import required Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns
sns.set(color_codes=True)

import warnings
warnings.filterwarnings("ignore")

Read in full datasets from school years 2013-2014, 2014-2015, 2015-2016, 2016-2017.

In [3]:
#csv path
path = "/Users/Olivia/SMUDS/Capstone/B/Analysis/2014/publicSchools2014.csv"
publicSchools14 = pd.read_csv(path, low_memory = False)
print(publicSchools14.info())

path = "/Users/Olivia/SMUDS/Capstone/B/Analysis/2015/publicSchools2015.csv"
publicSchools15 = pd.read_csv(path, low_memory = False)
print(publicSchools15.info())

path = "/Users/Olivia/SMUDS/Capstone/B/Analysis/2016/publicSchools2016.csv"
publicSchools16 = pd.read_csv(path, low_memory = False)
print(publicSchools16.info())

path = "/Users/Olivia/SMUDS/Capstone/B/Analysis/2017/publicSchools2017.csv"
publicSchools17 = pd.read_csv(path, low_memory = False)
print(publicSchools17.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2561 entries, 0 to 2560
Columns: 365 entries, vphone_ad to WhitePct
dtypes: float64(331), int64(3), object(31)
memory usage: 7.1+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2585 entries, 0 to 2584
Columns: 362 entries, vphone_ad to WhitePct
dtypes: float64(315), int64(3), object(44)
memory usage: 7.1+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2599 entries, 0 to 2598
Columns: 362 entries, vphone_ad to WhitePct
dtypes: float64(318), int64(3), object(41)
memory usage: 7.2+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2617 entries, 0 to 2616
Columns: 385 entries, vphone_ad to Number_Industry_Recognized_Crede
dtypes: float64(340), int64(3), object(42)
memory usage: 7.7+ MB
None

In [3]:
# #take out charter schools
# publicSchools17 = publicSchools17[publicSchools17['type_cd'] == 'P']
# publicSchools16 = publicSchools16[publicSchools16['type_cd'] == 'P']
# publicSchools15 = publicSchools15[publicSchools15['type_cd'] == 'P']
# publicSchools14 = publicSchools14[publicSchools14['type_cd'] == 'P']

### Low Performing School Definition:

“Low-performing schools are those that receive a school performance grade of D or F and a school growth score of "met expected growth" or "not met expected growth" as defined by G.S. 115C-83.15.” (G.S. 115C-105.37(a)), and

http://www.dpi.state.nc.us/schooltransformation/low-performing/

In [4]:
#create new column that equals 1 if low Performing
publicSchools14['LPS'] = np.where(publicSchools14['SPG Grade'].isin(['F', 'D'])&
                            publicSchools14['EVAAS Growth Status'].isin(['NotMet', 'Met']),
                            1, 0)

publicSchools15['LPS'] = np.where(publicSchools15['SPG Grade'].isin(['F', 'D'])&
                            publicSchools15['EVAAS Growth Status'].isin(['NotMet', 'Met']),
                            1, 0)

publicSchools16['LPS'] = np.where(publicSchools16['SPG Grade'].isin(['F', 'D'])&
                            publicSchools16['EVAAS Growth Status'].isin(['NotMet', 'Met']),
                            1, 0)

publicSchools17['LPS'] = np.where(publicSchools17['SPG Grade'].isin(['F', 'D'])&
                            publicSchools17['EVAAS Growth Status'].isin(['NotMet', 'Met']),
                            1, 0)

In [5]:
## Get the unit_codes of the low performing schools for each year and create new columns in the 2017 dataset
## to reflect the years of low performance
unit_codes_14 = publicSchools14['unit_code'][publicSchools14.LPS == 1]
unit_codes_15 = publicSchools15['unit_code'][publicSchools15.LPS == 1]
unit_codes_16 = publicSchools16['unit_code'][publicSchools16.LPS == 1]
unit_codes_17 = publicSchools17['unit_code'][publicSchools17.LPS == 1]

In [6]:
##Creat columns in publicSchools17 dataset
publicSchools17['LPS_14'] = np.where(publicSchools17['unit_code'].isin(unit_codes_14), 1, 0)
print('************** 2014 **************')
print('Num Public Schools Low Performing 2013-14: ', len(unit_codes_14))
print('Num Schools Still Running in 2017: ', len(publicSchools17.LPS_14[publicSchools17.LPS_14 ==1]))
print('Difference: ', (len(unit_codes_14) - len(publicSchools17.LPS_14[publicSchools17.LPS_14 ==1])))

publicSchools17['LPS_15'] = np.where(publicSchools17['unit_code'].isin(unit_codes_15), 1, 0)
print('************** 2015 **************')
print('Num Public Schools Low Performing 2014-15: ', len(unit_codes_15))
print('Num Schools Still Running in 2017: ', len(publicSchools17.LPS_15[publicSchools17.LPS_15 ==1]))
print('Difference: ', (len(unit_codes_15) - len(publicSchools17.LPS_15[publicSchools17.LPS_15 ==1])))

publicSchools17['LPS_16'] = np.where(publicSchools17['unit_code'].isin(unit_codes_16), 1, 0)
print('************** 2016 **************')
print('Num Public Schools Low Performing 2015-16: ', len(unit_codes_16))
print('Num Schools Still Running in 2017: ', len(publicSchools17.LPS_16[publicSchools17.LPS_16 ==1]))
print('Difference: ', (len(unit_codes_16) - len(publicSchools17.LPS_16[publicSchools17.LPS_16 ==1])))

publicSchools17['LPS_17'] = np.where(publicSchools17['unit_code'].isin(unit_codes_17), 1, 0)
print('************** 2014 **************')
print('Num Public Schools Low Performing 2016-17: ', len(unit_codes_17))
print('Num Schools Still Running in 2017: ', len(publicSchools17.LPS_17[publicSchools17.LPS_17 ==1]))
print('Difference: ', (len(unit_codes_17) - len(publicSchools17.LPS_17[publicSchools17.LPS_17 ==1])))

************** 2014 **************
Num Public Schools Low Performing 2013-14:  615
Num Schools Still Running in 2017:  600
Difference:  15
************** 2015 **************
Num Public Schools Low Performing 2014-15:  580
Num Schools Still Running in 2017:  572
Difference:  8
************** 2016 **************
Num Public Schools Low Performing 2015-16:  488
Num Schools Still Running in 2017:  485
Difference:  3
************** 2014 **************
Num Public Schools Low Performing 2016-17:  505
Num Schools Still Running in 2017:  505
Difference:  0

In [7]:
publicSchools17 = publicSchools17.drop(columns = 'LPS', axis=1)

## Number of times the school has been low performing

In [8]:
## Times low performing 
RLPS_series = []
for index, row in publicSchools17.iterrows():
    if row['LPS_14'] + row['LPS_15'] + row['LPS_16'] + row['LPS_17']  == 1:
        RLPS_series.append(1)
    elif row['LPS_14'] + row['LPS_15'] + row['LPS_16'] + row['LPS_17']  == 2:
        RLPS_series.append(2)
    elif row['LPS_14'] + row['LPS_15'] + row['LPS_16'] + row['LPS_17']  == 3:
        RLPS_series.append(3)
    elif row['LPS_14'] + row['LPS_15'] + row['LPS_16'] + row['LPS_17']  == 4:
        RLPS_series.append(4)
    else: 
        RLPS_series.append(0)
print(np.unique(RLPS_series))
publicSchools17['RLPS'] = RLPS_series

[0 1 2 3 4]

In [9]:
## Check Work: 
school_LPS_1 = publicSchools17.unit_code[publicSchools17['RLPS'] == 1]
school_LPS_2 = publicSchools17.unit_code[publicSchools17['RLPS'] == 2]
school_LPS_3 = publicSchools17.unit_code[publicSchools17['RLPS'] == 3]
school_LPS_4 = publicSchools17.unit_code[publicSchools17['RLPS'] == 4]
school_LPS_0 = publicSchools17.unit_code[publicSchools17['RLPS'] == 0]


print('Number of Schools Low Performing One Year: ', (school_LPS_1.count()))
print('Number of Schools Low Performing Two Years: ', (school_LPS_2.count()))
print('Number of Schools Low Performing Three Years: ', (school_LPS_3.count()))
print('Number of Schools Low Performing Four Years: ', (school_LPS_4.count()))
print('Number of Schools Low Performing Never: ', (school_LPS_0.count()))

Number of Schools Low Performing One Year:  263
Number of Schools Low Performing Two Years:  227
Number of Schools Low Performing Three Years:  203
Number of Schools Low Performing Four Years:  209
Number of Schools Low Performing Never:  1715

In [10]:
outputDir = '/Users/Olivia/SMUDS/Capstone/B/Analysis/RLPS/data/'
#Save the interim dataset to a .csv file
publicSchools17.to_csv(outputDir + 'publicSchools17EDA.csv', sep=',', index=False)

## Create Machine Learning Dataset for 2017

## Define Missing Data Thresholds

In [11]:
schoolData = publicSchools17.copy()

In [12]:
#Missing Data Threshold (Per Column)
missingThreshold = 0.95

#Unique Value Threshold (Per Column)
#Delete Columns >  uniqueThreshold unique values prior to one-hot encoding. 
#(each unique value becomes a new column during one-hot encoding)
uniqueThreshold = 25

print('*********Start: Beginning Column and Row Counts********************************************')
schoolData.info(verbose=False)

#Select only public schools as charter schools are missing data for many columns.
schoolData = schoolData[(schoolData['type_cd'] == 'P') & (schoolData['student_num'] > 0)]

print('\r\n*********After: Selecting Only Public School Campuses**********************************')
schoolData.info(verbose=False)

#Save primary key
unit_code = schoolData['unit_code']
#Convert zip code to string
schoolData['szip_ad'] = schoolData['szip_ad'].astype('object')

*********Start: Beginning Column and Row Counts********************************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2617 entries, 0 to 2616
Columns: 390 entries, vphone_ad to RLPS
dtypes: float64(340), int64(8), object(42)
memory usage: 7.8+ MB

*********After: Selecting Only Public School Campuses**********************************
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2443 entries, 2 to 2616
Columns: 390 entries, vphone_ad to RLPS
dtypes: float64(340), int64(8), object(42)
memory usage: 7.3+ MB

### Impute Missing Racial Composition Data

In [13]:
#Get Student Body Racial Composition Fields
raceCompositionFields = schoolData.filter(regex='Indian|Asian|Hispanic|Black|White|PacificIsland|TwoOrMore|Minority')\
                                  .filter(regex='Pct').columns
    
rowsBefore = schoolData[raceCompositionFields].isnull().T.any().T.sum()

#Update missing race values with the district average when avaiable (No district averages for charter schools) 
schoolData[raceCompositionFields] = schoolData.groupby('District Name')[raceCompositionFields]\
                                              .transform(lambda x: x.fillna(x.mean()))

    #Review dataset contents after Racial Composition Imputation
print('*********After: Updating Missing Racial Compostion Values****************************')   
rowsAfter = schoolData[raceCompositionFields].isnull().T.any().T.sum()
rowsUpdated = rowsBefore - rowsAfter
print ('Rows Updated / Imputed: ', rowsUpdated) 
print('\r\nTotal Rows Missing Racial Compositions By District Name') 
schoolData['District Name'][schoolData[raceCompositionFields].isnull().T.any().T].value_counts()
print(schoolData['District Name'][schoolData[raceCompositionFields].isnull().T.any().T].value_counts())

*********After: Updating Missing Racial Compostion Values****************************
Rows Updated / Imputed:  0

Total Rows Missing Racial Compositions By District Name
Series([], Name: District Name, dtype: int64)

### Remove Columns with the same data in all rows

In [14]:
#Remove any fields that have the same value in all rows
UniqueValueCounts = schoolData.nunique(dropna=False)
SingleValueCols = UniqueValueCounts[UniqueValueCounts == 1].index
schoolData = schoolData.drop(SingleValueCols, axis=1)

#Review dataset contents after drops
print('*********After: Removing columns with the same value in every row.*******************')
schoolData.info(verbose=False)
print ('\r\nColumns Deleted: ', len(SingleValueCols))
print('Columns:', list(SingleValueCols))

*********After: Removing columns with the same value in every row.*******************
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2443 entries, 2 to 2616
Columns: 265 entries, vphone_ad to RLPS
dtypes: float64(221), int64(5), object(39)
memory usage: 5.0+ MB

Columns Deleted:  125
Columns: ['year', 'state_ad', 'type_cd', 'closed_ind', 'new_ind', 'super_nm', 'State_Name', 'stem', 'total_expense_num', 'salary_expense_pct', 'benefits_expense_pct', 'services_expense_pct', 'supplies_expense_pct', 'instruct_equip_exp_pct', 'other_expense_pct', 'federal_perpupil_num', 'local_perpupil_num', 'state_perpupil_num', 'lea_benefits_expense_pct', 'lea_other_expense_pct', 'st_total_expense_num', 'st_salary_expense_pct', 'st_benefits_expense_pct', 'st_services_expense_pct', 'st_supplies_expense_pct', 'st_instruct_equip_exp_pct', 'st_other_expense_pct', 'st_federal_perpupil_num', 'st_local_perpupil_num', 'st_state_perpupil_num', 'building_expense_pct', 'lea_building_expense_pct', 'st_building_expense_pct', 'st_sat_avg_score_num', 'nat_sat_avg_score_num', 'st_sat_participation_pct', 'nat_sat_participation_pct', 'esea_attendance', 'lea_esea_attendance', 'st_ap_participation_pct', 'st_ap_pct_3_or_above', 'lea_ib_participation_pct', 'st_ib_participation_pct', 'st_ib_pct_4_or_above', 'ttl_crimes_num', 'st_stud_internet_comp_num', 'st_avg_age_media_collection', 'st_books_per_student', 'st_wap_num', 'st_wap_per_classroom', 'total_class_teacher_num', 'total_nbpts_num', 'prin_other_pct', 'prinyrs_0thru3_pct', 'prinyrs_4thru10_pct', 'prinyrs_11plus_pct', 'prin_advance_dgr_pct', '_1yr_prin_trnovr_pct', 'prin_male_pct', 'prin_female_pct', 'prin_black_pct', 'prin_white_pct', 'highqual_class_pct', 'lea_highqual_class_pct', 'lea_highqual_class_hp_pct', 'lea_highqual_class_lp_pct', 'lea_highqual_class_all_pct', 'lea_not_highqual_class_hp_pct', 'lea_not_highqual_class_lp_pct', 'lea_not_highqual_class_all_pct', 'st_highqual_class_pct', 'st_highqual_class_hp_pct', 'st_highqual_class_lp_pct', 'st_highqual_class_all_pct', 'st_not_highqual_class_hp_pct', 'st_not_highqual_class_lp_pct', 'st_not_highqual_class_all_pct', 'st_prinyrs_0thru3_pct', 'st_prinyrs_4thru10_pct', 'st_prinyrs_11plus_pct', 'st_prin_advance_dgr_pct', 'st_1yr_prin_trnovr_pct', 'st_prin_male_pct', 'st_prin_female_pct', 'st_prin_black_pct', 'st_prin_white_pct', 'st_prin_other_pct', 'Accomplished_PRIN_Standard 1_Pct', 'Accomplished_PRIN_Standard 2_Pct', 'Accomplished_PRIN_Standard 3_Pct', 'Accomplished_PRIN_Standard 4_Pct', 'Accomplished_PRIN_Standard 5_Pct', 'Accomplished_PRIN_Standard 6_Pct', 'Accomplished_PRIN_Standard 7_Pct', 'Developing_PRIN_Standard 1_Pct', 'Developing_PRIN_Standard 2_Pct', 'Developing_PRIN_Standard 3_Pct', 'Developing_PRIN_Standard 4_Pct', 'Developing_PRIN_Standard 5_Pct', 'Developing_PRIN_Standard 6_Pct', 'Developing_PRIN_Standard 7_Pct', 'Distinguished_PRIN_Standard 1_Pct', 'Distinguished_PRIN_Standard 2_Pct', 'Distinguished_PRIN_Standard 3_Pct', 'Distinguished_PRIN_Standard 4_Pct', 'Distinguished_PRIN_Standard 5_Pct', 'Distinguished_PRIN_Standard 6_Pct', 'Distinguished_PRIN_Standard 7_Pct', 'Does Not Meet Expected Growth_PRIN_School_Growth_Pct', 'Exceeds Expected Growth_PRIN_School_Growth_Pct', 'Meets Expected Growth_PRIN_School_Growth_Pct', 'Not Demostrated_PRIN_Standard 1_Pct', 'Not Demostrated_PRIN_Standard 2_Pct', 'Not Demostrated_PRIN_Standard 3_Pct', 'Not Demostrated_PRIN_Standard 4_Pct', 'Not Demostrated_PRIN_Standard 5_Pct', 'Not Demostrated_PRIN_Standard 6_Pct', 'Not Demostrated_PRIN_Standard 7_Pct', 'Proficient_PRIN_Standard 1_Pct', 'Proficient_PRIN_Standard 2_Pct', 'Proficient_PRIN_Standard 3_Pct', 'Proficient_PRIN_Standard 4_Pct', 'Proficient_PRIN_Standard 5_Pct', 'Proficient_PRIN_Standard 6_Pct', 'Proficient_PRIN_Standard 7_Pct']

## Remove Columns with Unique Data In All Rows

In [15]:
#Remove any fields that have unique values in every row
schoolDataRecordCt = schoolData.shape[0]
UniqueValueCounts = schoolData.apply(pd.Series.nunique)
AllUniqueValueCols = UniqueValueCounts[UniqueValueCounts == schoolDataRecordCt].index
schoolData = schoolData.drop(AllUniqueValueCols, axis=1)

#Review dataset contents after drops
print('*********After: Removing columns with unique values in every row.*******************')
schoolData.info(verbose=False)
print ('\r\nColumns Deleted: ', len(AllUniqueValueCols))

*********After: Removing columns with unique values in every row.*******************
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2443 entries, 2 to 2616
Columns: 263 entries, vphone_ad to RLPS
dtypes: float64(221), int64(5), object(37)
memory usage: 5.0+ MB

Columns Deleted:  2

### Remove identifying columns (unit code, school code)

In [16]:
#Remove any fields that have unique values in every row
schoolDataRecordCt = schoolData.shape[0]
UniqueValueCounts = schoolData.apply(pd.Series.nunique)
AllUniqueValueCols = UniqueValueCounts[UniqueValueCounts == schoolDataRecordCt].index
schoolData = schoolData.drop(AllUniqueValueCols, axis=1)

#Review dataset contents after drops
print('*********After: Removing columns with unique values in every row.*******************')
schoolData.info(verbose=False)
print ('\r\nColumns Deleted: ', len(AllUniqueValueCols))
print('Columns: ', AllUniqueValueCols)

*********After: Removing columns with unique values in every row.*******************
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2443 entries, 2 to 2616
Columns: 263 entries, vphone_ad to RLPS
dtypes: float64(221), int64(5), object(37)
memory usage: 4.9+ MB

Columns Deleted:  0
Columns:  Index([], dtype='object')

### Remove columns with all null values

In [17]:
#Remove any empty fields (null values in every row)
schoolDataRecordCt = schoolData.shape[0]
NullValueCounts = schoolData.isnull().sum()
NullValueCols = NullValueCounts[NullValueCounts == schoolDataRecordCt].index
schoolData = schoolData.drop(NullValueCols, axis=1)

#Review dataset contents after empty field drops
print('*********After: Removing columns with null / blank values in every row.*************')
schoolData.info(verbose=False)
print ('\r\nColumns Deleted: ', len(NullValueCols))
print ('Columns: ', list(NullValueCols))

*********After: Removing columns with null / blank values in every row.*************
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2443 entries, 2 to 2616
Columns: 263 entries, vphone_ad to RLPS
dtypes: float64(221), int64(5), object(37)
memory usage: 4.9+ MB

Columns Deleted:  0
Columns:  []

## Data Types

In [18]:
#Isolate continuous and categorical data types
#These are indexers into the schoolData dataframe and may be used similar to the schoolData dataframe 
sD_boolean = schoolData.loc[:, (schoolData.dtypes == bool) ]
sD_nominal = schoolData.loc[:, (schoolData.dtypes == object)]
sD_continuous = schoolData.loc[:, (schoolData.dtypes != bool) & (schoolData.dtypes != object)]
print ("Boolean Columns: ", sD_boolean.shape[1])
print ("Nominal Columns: ", sD_nominal.shape[1])
print ("Continuous Columns: ", sD_continuous.shape[1])
print ("Columns Accounted for: ", sD_nominal.shape[1] + sD_continuous.shape[1] + sD_boolean.shape[1])

Boolean Columns:  0
Nominal Columns:  37
Continuous Columns:  226
Columns Accounted for:  263

### Convert Booleans to 1s and 0s

In [19]:
#Convert Columns with values of nan, 'Y' as booleans
hasY = []
for x in schoolData.columns: 
    if ((['Y'] in schoolData[x].unique()) & (len(schoolData[x].unique()) == 2)):
        hasY.append(x)
print(hasY)

for x in hasY: 
# Map flag fields into bool
    schoolData[x] = schoolData[x].map({'Y':1, np.nan:0})

schoolData['esea_status'] = schoolData['esea_status'].map({'P':'Esea_Pass', 'F':'Esea_Fail', np.nan:'Non_Esea'})
schoolData['Grad_project_status'] = schoolData['Grad_project_status'].map({'Y':1, 'N':0, np.nan:0})

#Boolean Columns
sD_boolean = schoolData.loc[:, (schoolData.dtypes == bool) ]
print ("Boolean Columns: ", sD_boolean.shape[1])

['title1_type_cd', 'clp_ind', 'focus_clp_ind', 'summer_program_ind', 'asm_no_spg_ind', 'no_data_spg_ind']
Boolean Columns:  0

### Eliminate columns with < 5% data

In [20]:
#Eliminate continuous columns with more than missingThreshold percentage of missing values
schoolDataRecordCt = sD_continuous.shape[0]
missingValueLimit = schoolDataRecordCt * missingThreshold
NullValueCounts = sD_continuous.isnull().sum()
NullValueCols = NullValueCounts[NullValueCounts >= missingValueLimit].index
schoolData = schoolData.drop(NullValueCols, axis=1)

#Review dataset contents after empty field drops
print('*********After: Removing columns with >= missingThreshold % of missing values******')
schoolData.info(verbose=False)
print ('\r\nColumns Deleted: ', len(NullValueCols))
print ('\r\nColumns: ', list(NullValueCols))

*********After: Removing columns with >= missingThreshold % of missing values******
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2443 entries, 2 to 2616
Columns: 254 entries, vphone_ad to RLPS
dtypes: float64(212), int64(12), object(30)
memory usage: 4.8+ MB

Columns Deleted:  9

Columns:  ['13_Size', 'ib_participation_pct', 'ib_pct_4_or_above', 'LEP_Limited English Proficiency_ENROLL_sch_pct', 'MA_Asian_ENROLL_sch_pct', 'MAN_American Indian_ENROLL_sch_pct', 'MM_Multiracial_ENROLL_sch_pct', 'WDIS_Students With Disabilities_ENROLL_sch_pct', 'EDUC_Concentrator_Ct']

### Delete columns with more than 25 unique values before one hot encoding

In [21]:
#Delete categorical columns with > 25 unique values (Each unique value becomes a column during one-hot encoding)
oneHotUniqueValueCounts = schoolData[sD_nominal.columns].apply(lambda x: x.nunique())
oneHotUniqueValueCols = oneHotUniqueValueCounts[oneHotUniqueValueCounts >= uniqueThreshold].index
schoolData.drop(oneHotUniqueValueCols, axis=1, inplace=True) 

#Review dataset contents one hot high unique value drops
print('*********After: Removing columns with >= uniqueThreshold unique values***********')
schoolData.info(verbose=False)
print ('\r\nColumns Deleted: ', len(oneHotUniqueValueCols))
print ('\r\nColumns : ', list(oneHotUniqueValueCols))

*********After: Removing columns with >= uniqueThreshold unique values***********
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2443 entries, 2 to 2616
Columns: 240 entries, category_cd to RLPS
dtypes: float64(212), int64(12), object(16)
memory usage: 4.5+ MB

Columns Deleted:  14

Columns :  ['vphone_ad', 'street_ad', 'scity_ad', 'szip_ad', 'url_ad', 'grade_range_cd', 'cover_letter_ad', 'Lea_Name', 'url', 'District Name', 'School Name', 'grades_BYOD', 'grades_1_to_1_access', 'SRC_Grades_Devices_Sent_Home']

### One hot encode categorical variables

In [22]:
#Isolate remaining categorical variables
begColumnCt = len(schoolData.columns)
sD_nominal = schoolData.loc[:, (schoolData.dtypes == object)]

#one hot encode categorical variables
schoolData = pd.get_dummies(data=schoolData, 
                       columns=sD_nominal, drop_first=True)

#Determine change in column count
endColumnCt = len(schoolData.columns)
columnsAdded = endColumnCt - begColumnCt

#Review dataset contents one hot high unique value drops
print ('Columns To One-Hot Encode: ', len(sD_nominal.columns), list(sD_nominal.columns))
print('\r\n*********After: Adding New Columns Via One-Hot Encoding*************************')
schoolData.info(verbose=False)
print ('\r\nNew Columns Created Via One-Hot Encoding: ', columnsAdded)

Columns To One-Hot Encode:  16 ['category_cd', 'calendar_type_txt', 'sna_pgm_type_cd', 'school_type_txt', 'calendar_only_txt', 'esea_status', 'SBE District', 'SPG Grade', 'Reading SPG Grade', 'Math SPG Grade', 'EVAAS Growth Status', 'State Gap Compared', 'Category_Cd', 'Byod', '_1_to_1_access', 'SRC_devices_sent_home']

*********After: Adding New Columns Via One-Hot Encoding*************************
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2443 entries, 2 to 2616
Columns: 283 entries, title1_type_cd to SRC_devices_sent_home_Yes
dtypes: float64(212), int64(12), uint8(59)
memory usage: 4.3 MB

New Columns Created Via One-Hot Encoding:  43

### Impute remaining missing values to zero

In [23]:
#Print out all the missing value rows
pd.set_option('display.max_rows', 1000)

print('\r\n*********The Remaining Missing Values Below will be set to Zero!*************************')

#Check for Missing values 
missing_values = schoolData.isnull().sum().reset_index()
missing_values.columns = ['Variable Name', 'Number Missing Values']
missing_values = missing_values[missing_values['Number Missing Values'] > 0] 
missing_values

*********The Remaining Missing Values Below will be set to Zero!*************************

                                         Variable Name  Number Missing Values
10                                             00_Size                   1143
11                                             01_Size                   1144
12                                             02_Size                   1142
13                                             03_Size                   1149
14                                             04_Size                   1139
15                                             05_Size                   1170
16                                             06_Size                   1853
17                                             07_Size                   1884
18                                             08_Size                   1883
19                                             09_Size                   1985
20                                             10_Size                   2008
21                                             11_Size                   2017
22                                             12_Size                   2040
23                                        Biology_Size                   1895
24                                     English II_Size                   1900
25                                         Math I_Size                   1413
34                                           SPG Score                    130
35                                   Reading SPG Score                    616
36                                      Math SPG Score                    616
37                                  EVAAS Growth Score                    142
38                           Overall Achievement Score                    130
39                                       Reading Score                    616
40                                          Math Score                    616
41                                       Science Score                    701
42                                     NC Math 1 Score                   1458
43                                    English II Score                   1951
44                                       Biology Score                   1948
45                                           ACT Score                   1946
46                                  ACT WorkKeys Score                   2029
47                                   Passing NC Math 3                   1949
48                 4-Year Cohort Graduation Rate Score                   1948
49                                  ACT_pTarget_PctMet                   1959
50                          ACTWorkKeys_pTarget_PctMet                   2083
51                       CurrentYearEOC_pTarget_PctMet                   1582
52                             MathGr10_pTarget_PctMet                   1956
53                            MathGr3-8_pTarget_PctMet                    583
54                          ReadingGr10_pTarget_PctMet                   1956
55                         ReadingGr3-8_pTarget_PctMet                    583
56                              SciGr11_pTarget_PctMet                   1962
57                             SciGr5&8_pTarget_PctMet                    749
58                         TotalTargets_pTarget_PctMet                     68
59                                   sat_avg_score_num                   1986
60                               lea_sat_avg_score_num                      6
61                               sat_participation_pct                   1986
62                           lea_sat_participation_pct                      6
63                                ap_participation_pct                   2097
64                            lea_ap_participation_pct                    263
65                                   ap_pct_3_or_above                   2055
66                               lea_ap_pct_3_or_above                     64
67                               lea_ib_pct_4_or_above                   1314
68                           total_specialized_courses                   1855
69                                       ap_ib_courses                   2040
70                                         cte_courses                   1885
71                                univ_college_courses                   1989
72                       lea_total_specialized_courses                   1855
73                                   lea_ap_ib_courses                   1864
74                                     lea_cte_courses                   1855
75                            lea_univ_college_courses                   1858
76                        st_total_specialized_courses                   1855
77                                    st_ap_ib_courses                   1855
78                                      st_cte_courses                   1855
79                             st_univ_college_courses                   1855
80   ALL_All Students (Total or Subtotal_ENROLL_sch...                   1927
81    ECODIS_Economically Disadvantaged_ENROLL_sch_pct                   2038
82                             F_Female_ENROLL_sch_pct                   1935
83                               M_Male_ENROLL_sch_pct                   1942
84                             MB_Black_ENROLL_sch_pct                   2086
85                         MHL_Hispanic_ENROLL_sch_pct                   2285
86                             MW_White_ENROLL_sch_pct                   1983
92                              stud_internet_comp_num                      8
104                                  digital_media_pct                    142
105                           avg_age_media_collection                    132
106                                  books_per_student                    147
107                       lea_avg_age_media_collection                    132
108                              lea_books_per_student                    147
109                                            wap_num                     18
110                                  wap_per_classroom                     18
113                                flicensed_teach_pct                      2
114                                  tchyrs_0thru3_pct                      2
115                                 tchyrs_4thru10_pct                      2
116                                  tchyrs_11plus_pct                      2
117                                    class_teach_num                      2
118                                          nbpts_num                      2
119                                    advance_dgr_pct                      2
120                               _1yr_tchr_trnovr_pct                     23
121                                emer_prov_teach_pct                   2139
122                                  lateral_teach_pct                    881
131                            lea_emer_prov_teach_pct                    954
132                              lea_lateral_teach_pct                    107
143                              0-3 Years_Exp_Pct_Tch                      2
144                              10+ Years_Exp_Pct_Tch                      2
145                             4-10 Years_Exp_Pct_Tch                      2
149                   Accomplished_TCHR_Standard 1_Pct                      9
150                   Accomplished_TCHR_Standard 2_Pct                      9
151                   Accomplished_TCHR_Standard 3_Pct                      9
152                   Accomplished_TCHR_Standard 4_Pct                      9
153                   Accomplished_TCHR_Standard 5_Pct                      9
154                     Developing_TCHR_Standard 1_Pct                      9
155                     Developing_TCHR_Standard 2_Pct                      9
156                     Developing_TCHR_Standard 3_Pct                      9
157                     Developing_TCHR_Standard 4_Pct                      9
158                     Developing_TCHR_Standard 5_Pct                      9
159                  Distinguished_TCHR_Standard 1_Pct                      9
160                  Distinguished_TCHR_Standard 2_Pct                      9
161                  Distinguished_TCHR_Standard 3_Pct                      9
162                  Distinguished_TCHR_Standard 4_Pct                      9
163                  Distinguished_TCHR_Standard 5_Pct                      9
164  Does Not Meet Expected Growth_TCHR_Student Gro...                     54
165    Exceeds Expected Growth_TCHR_Student Growth_Pct                     54
166      Meets Expected Growth_TCHR_Student Growth_Pct                     54
167                Not Demostrated_TCHR_Standard 1_Pct                      9
168                Not Demostrated_TCHR_Standard 2_Pct                      9
169                Not Demostrated_TCHR_Standard 3_Pct                      9
170                Not Demostrated_TCHR_Standard 4_Pct                      9
171                Not Demostrated_TCHR_Standard 5_Pct                      9
172                     Proficient_TCHR_Standard 1_Pct                      9
173                     Proficient_TCHR_Standard 2_Pct                      9
174                     Proficient_TCHR_Standard 3_Pct                      9
175                     Proficient_TCHR_Standard 4_Pct                      9
176                     Proficient_TCHR_Standard 5_Pct                      9
201                                      Gr_6_Pct_Prof                   1787
202                                      Gr_9_Pct_Prof                   1864
204                               AAVC_Concentrator_Ct                   2192
205                               AGNR_Concentrator_Ct                   2081
206                               ARCH_Concentrator_Ct                   2103
207                                BMA_Concentrator_Ct                   2079
208                               FINA_Concentrator_Ct                   2315
209                               HLTH_Concentrator_Ct                   2090
210                               HOSP_Concentrator_Ct                   2064
211                               HUMA_Concentrator_Ct                   2232
212                               INFO_Concentrator_Ct                   2080
213                                LAW_Concentrator_Ct                   2256
214                               MANU_Concentrator_Ct                   2184
215                               MRKT_Concentrator_Ct                   2211
216                               STEM_Concentrator_Ct                   2202
217                               TRAN_Concentrator_Ct                   2221
218                   Number_Industry_Recognized_Crede                   1961

In [24]:
#Replace all remaining NaN with 0
schoolData = schoolData.fillna(0)

#Check for Missing values after final imputation 
missing_values = schoolData.isnull().sum().reset_index()
missing_values.columns = ['Variable Name', 'Number Missing Values']
missing_values = missing_values[missing_values['Number Missing Values'] > 0] 
missing_values

Empty DataFrame
Columns: [Variable Name, Number Missing Values]
Index: []

## Scale Expression of Percentages

In [25]:
PercentageFields = schoolData.filter(regex='pct|Pct|percent|Percent').columns
converted = []
for x in PercentageFields:
    if(schoolData[x].max() > 1):
        converted.append(x)
        schoolData[x] = schoolData[x]/100
print('Number of Percentage Fields:', len(PercentageFields))
print('Percentage Fields Converted to between 0 and 1: ', len(converted))

Number of Percentage Fields: 117
Percentage Fields Converted to between 0 and 1:  10

## Correlated Features

In [26]:
# calculate the correlation matrix
corr_matrix  = schoolData.corr().abs()

# Select upper triangle of correlation matrix
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))

# Find index of feature columns with correlation greater than 0.95
to_drop = [column for column in upper.columns if any(upper[column] > 0.95)]

In [27]:
#Get all of the correlation values > 95%
x = np.where(upper > 0.95)

#Display all field combinations with > 95% correlation
cf = pd.DataFrame()
cf['Field1'] = upper.columns[x[1]]
cf['Field2'] = upper.index[x[0]]

#Get the correlation values for every field combination. (There must be a more pythonic way to do this!)
corr = [0] * len(cf)
for i in range(0, len(cf)):
    corr[i] =  upper[cf['Field1'][i]][cf['Field2'][i]] 
    
cf['Correlation'] = corr

print ('There are ', str(len(cf['Field1'])), ' field correlations > 95%.')
cf

There are  101  field correlations > 95%.

,Field1,Field2,Correlation
0,SPG Grade_I,no_data_spg_ind,1.000000
1,class_teach_num,student_num,0.967407
2,lea_class_teach_num,lea_avg_student_num,0.970002
3,st_class_teach_num,st_avg_student_num,0.999101
4,st_advance_dgr_pct,st_avg_student_num,0.985325
5,01_Size,00_Size,0.951996
6,08_Size,07_Size,0.973609
7,English II_Size,Biology_Size,0.967887
8,Overall Achievement Score,SPG Score,0.988052
9,Math SPG Score,Reading SPG Score,0.975327
10,Reading Score,Reading SPG Score,0.993509
11,Math Score,Reading SPG Score,0.962299
12,Reading Score,Math SPG Score,0.968500
13,Math Score,Math SPG Score,0.992156
14,Math Score,Reading Score,0.966296
15,Biology Score,English II Score,0.963000
16,ACT Score,English II Score,0.952752
17,4-Year Cohort Graduation Rate Score,Passing NC Math 3,0.994651
18,SciGr11_pTarget_PctMet,ACT_pTarget_PctMet,0.963846
19,ReadingGr10_pTarget_PctMet,MathGr10_pTarget_PctMet,0.979954
20,ReadingGr3-8_pTarget_PctMet,MathGr3-8_pTarget_PctMet,0.999506
21,ap_ib_courses,ap_participation_pct,0.971766
22,lea_total_specialized_courses,total_specialized_courses,0.997769
23,lea_cte_courses,total_specialized_courses,0.987263
24,st_total_specialized_courses,total_specialized_courses,0.996588
25,st_ap_ib_courses,total_specialized_courses,0.996588
26,st_cte_courses,total_specialized_courses,0.996588
27,st_univ_college_courses,total_specialized_courses,0.996588
28,st_tchyrs_11plus_pct,total_specialized_courses,0.978789
29,lea_cte_courses,lea_total_specialized_courses,0.989790
30,st_total_specialized_courses,lea_total_specialized_courses,0.999056
31,st_ap_ib_courses,lea_total_specialized_courses,0.999056
32,st_cte_courses,lea_total_specialized_courses,0.999056
33,st_univ_college_courses,lea_total_specialized_courses,0.999056
34,st_tchyrs_11plus_pct,lea_total_specialized_courses,0.979929
35,st_total_specialized_courses,lea_cte_courses,0.990735
36,st_ap_ib_courses,lea_cte_courses,0.990735
37,st_cte_courses,lea_cte_courses,0.990735
38,st_univ_college_courses,lea_cte_courses,0.990735
39,st_tchyrs_11plus_pct,lea_cte_courses,0.970809
40,st_ap_ib_courses,st_total_specialized_courses,1.000000
41,st_cte_courses,st_total_specialized_courses,1.000000
42,st_univ_college_courses,st_total_specialized_courses,1.000000
43,st_tchyrs_11plus_pct,st_total_specialized_courses,0.980840
44,st_cte_courses,st_ap_ib_courses,1.000000
45,st_univ_college_courses,st_ap_ib_courses,1.000000
46,st_tchyrs_11plus_pct,st_ap_ib_courses,0.980840
47,st_univ_college_courses,st_cte_courses,1.000000
48,st_tchyrs_11plus_pct,st_cte_courses,0.980840
49,st_tchyrs_11plus_pct,st_univ_college_courses,0.980840
50,F_Female_ENROLL_sch_pct,ALL_All Students (Total or Subtotal_ENROLL_sch...,0.983822
51,M_Male_ENROLL_sch_pct,ALL_All Students (Total or Subtotal_ENROLL_sch...,0.972043
52,st_tchyrs_4thru10_pct,st_crime_per_c_num,0.967625
53,st_lateral_teach_pct,st_crime_per_c_num,0.974655
54,category_cd_T,st_expelled_per_c_num,1.000000
55,Category_Cd_T,st_expelled_per_c_num,1.000000
56,lea_avg_age_media_collection,avg_age_media_collection,0.996030
57,0-3 Years_Exp_Pct_Tch,tchyrs_0thru3_pct,1.000000
58,4-10 Years_Exp_Pct_Tch,tchyrs_4thru10_pct,1.000000
59,10+ Years_Exp_Pct_Tch,tchyrs_11plus_pct,1.000000
60,lea_lateral_teach_pct,lea_flicensed_teach_pct,0.989316
61,st_lateral_teach_pct,st_tchyrs_4thru10_pct,0.961796
62,st_advance_dgr_pct,st_class_teach_num,0.981841
63,Not Demostrated_TCHR_Standard 3_Pct,Not Demostrated_TCHR_Standard 2_Pct,0.973954
64,Not Demostrated_TCHR_Standard 5_Pct,Not Demostrated_TCHR_Standard 2_Pct,0.956045
65,AsianPct,AsianFemalePct,0.980606
66,AsianPct,AsianMalePct,0.983372
67,BlackPct,BlackFemalePct,0.958851
68,BlackPct,BlackMalePct,0.965391
69,HispanicPct,HispanicFemalePct,0.976295
70,HispanicPct,HispanicMalePct,0.977670
71,IndianMalePct,IndianFemalePct,0.972999
72,IndianPct,IndianFemalePct,0.992872
73,IndianPct,IndianMalePct,0.993573
74,WhiteMalePct,MinorityFemalePct,0.952432
75,MinorityPct,MinorityMalePct,0.955630
76,WhiteFemalePct,MinorityMalePct,0.956285
77,WhitePct,MinorityMalePct,0.955630
78,WhiteFemalePct,MinorityPct,0.973828
79,WhiteMalePct,MinorityPct,0.976143
80,WhitePct,MinorityPct,1.000000
81,WhitePct,WhiteFemalePct,0.973828
82,WhitePct,WhiteMalePct,0.976143
83,Category_Cd_E,category_cd_E,1.000000
84,Category_Cd_H,category_cd_H,1.000000
85,Category_Cd_I,category_cd_I,1.000000
86,Category_Cd_M,category_cd_M,1.000000
87,Category_Cd_T,category_cd_T,1.000000
88,sna_pgm_type_cd_H,calendar_type_txt_Hospital School,1.000000
89,school_type_txt_Hospital School,calendar_type_txt_Hospital School,1.000000
90,sna_pgm_type_cd_M,"calendar_type_txt_Magnet School, Traditional C...",1.000000
91,sna_pgm_type_cd_N,"calendar_type_txt_Magnet School, Year-Round Ca...",1.000000
92,sna_pgm_type_cd_R,"calendar_type_txt_Regular School, Traditional ...",1.000000
93,sna_pgm_type_cd_Y,"calendar_type_txt_Regular School, Year-Round C...",1.000000
94,sna_pgm_type_cd_S,"calendar_type_txt_Special Education, Tradition...",1.000000
95,school_type_txt_Special Education,"calendar_type_txt_Special Education, Tradition...",1.000000
96,sna_pgm_type_cd_V,"calendar_type_txt_Vocational Education, Tradit...",1.000000
97,school_type_txt_Vocational Education,"calendar_type_txt_Vocational Education, Tradit...",1.000000
98,school_type_txt_Hospital School,sna_pgm_type_cd_H,1.000000
99,school_type_txt_Special Education,sna_pgm_type_cd_S,1.000000
100,school_type_txt_Vocational Education,sna_pgm_type_cd_V,1.000000

In [28]:
print ('Dropping the following ', str(len(to_drop)), ' highly correlated fields.')
to_drop

Dropping the following  62  highly correlated fields.

['01_Size',
 '08_Size',
 'English II_Size',
 'Math SPG Score',
 'Overall Achievement Score',
 'Reading Score',
 'Math Score',
 'Biology Score',
 'ACT Score',
 '4-Year Cohort Graduation Rate Score',
 'ReadingGr10_pTarget_PctMet',
 'ReadingGr3-8_pTarget_PctMet',
 'SciGr11_pTarget_PctMet',
 'ap_ib_courses',
 'lea_total_specialized_courses',
 'lea_cte_courses',
 'st_total_specialized_courses',
 'st_ap_ib_courses',
 'st_cte_courses',
 'st_univ_college_courses',
 'F_Female_ENROLL_sch_pct',
 'M_Male_ENROLL_sch_pct',
 'lea_avg_age_media_collection',
 'class_teach_num',
 'lea_class_teach_num',
 'lea_lateral_teach_pct',
 'st_tchyrs_4thru10_pct',
 'st_tchyrs_11plus_pct',
 'st_class_teach_num',
 'st_advance_dgr_pct',
 'st_lateral_teach_pct',
 '0-3 Years_Exp_Pct_Tch',
 '10+ Years_Exp_Pct_Tch',
 '4-10 Years_Exp_Pct_Tch',
 'Not Demostrated_TCHR_Standard 3_Pct',
 'Not Demostrated_TCHR_Standard 5_Pct',
 'AsianPct',
 'BlackPct',
 'HispanicPct',
 'IndianMalePct',
 'IndianPct',
 'MinorityPct',
 'WhiteFemalePct',
 'WhiteMalePct',
 'WhitePct',
 'category_cd_T',
 'sna_pgm_type_cd_H',
 'sna_pgm_type_cd_M',
 'sna_pgm_type_cd_N',
 'sna_pgm_type_cd_R',
 'sna_pgm_type_cd_S',
 'sna_pgm_type_cd_V',
 'sna_pgm_type_cd_Y',
 'school_type_txt_Hospital School',
 'school_type_txt_Special Education',
 'school_type_txt_Vocational Education',
 'SPG Grade_I',
 'Category_Cd_E',
 'Category_Cd_H',
 'Category_Cd_I',
 'Category_Cd_M',
 'Category_Cd_T']

In [29]:
#Check columns before drop 
print('\r\n*********Before: Dropping Highly Correlated Fields*************************************')
schoolData.info(verbose=False)

# Drop the highly correlated features from our training data 
schoolData = schoolData.drop(to_drop, axis=1)

#Check columns after drop 
print('\r\n*********After: Dropping Highly Correlated Fields**************************************')
schoolData.info(verbose=False)

*********Before: Dropping Highly Correlated Fields*************************************
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2443 entries, 2 to 2616
Columns: 283 entries, title1_type_cd to SRC_devices_sent_home_Yes
dtypes: float64(212), int64(12), uint8(59)
memory usage: 4.3 MB

*********After: Dropping Highly Correlated Fields**************************************
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2443 entries, 2 to 2616
Columns: 221 entries, title1_type_cd to SRC_devices_sent_home_Yes
dtypes: float64(167), int64(12), uint8(42)
memory usage: 3.5 MB

In [30]:
outputDir = '/Users/Olivia/SMUDS/Capstone/B/Analysis/RLPS/data/'
#Restore the unit_code before saving
schoolData['unit_code'] = unit_code
#Save the final dataset to a .csv file
schoolData.to_csv(outputDir + 'RLPS2017Classification' + '_ML.csv', sep=',', index=False)

In [31]:
print('*********FINAL DATASET DETAILS*********************************************************\r\n')
schoolData.info(verbose=True)

*********FINAL DATASET DETAILS*********************************************************

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2443 entries, 2 to 2616
Data columns (total 222 columns):
title1_type_cd                                                  int64
clp_ind                                                         int64
focus_clp_ind                                                   int64
summer_program_ind                                              int64
asm_no_spg_ind                                                  int64
no_data_spg_ind                                                 int64
student_num                                                     float64
lea_avg_student_num                                             float64
st_avg_student_num                                              float64
Grad_project_status                                             int64
00_Size                                                         float64
02_Size                                                         float64
03_Size                                                         float64
04_Size                                                         float64
05_Size                                                         float64
06_Size                                                         float64
07_Size                                                         float64
09_Size                                                         float64
10_Size                                                         float64
11_Size                                                         float64
12_Size                                                         float64
Biology_Size                                                    float64
Math I_Size                                                     float64
lea_total_expense_num                                           float64
lea_salary_expense_pct                                          float64
lea_services_expense_pct                                        float64
lea_supplies_expense_pct                                        float64
lea_instruct_equip_exp_pct                                      float64
lea_federal_perpupil_num                                        float64
lea_local_perpupil_num                                          float64
lea_state_perpupil_num                                          float64
SPG Score                                                       float64
Reading SPG Score                                               float64
EVAAS Growth Score                                              float64
Science Score                                                   float64
NC Math 1 Score                                                 float64
English II Score                                                float64
ACT WorkKeys Score                                              float64
Passing NC Math 3                                               float64
ACT_pTarget_PctMet                                              float64
ACTWorkKeys_pTarget_PctMet                                      float64
CurrentYearEOC_pTarget_PctMet                                   float64
MathGr10_pTarget_PctMet                                         float64
MathGr3-8_pTarget_PctMet                                        float64
SciGr5&8_pTarget_PctMet                                         float64
TotalTargets_pTarget_PctMet                                     float64
sat_avg_score_num                                               float64
lea_sat_avg_score_num                                           float64
sat_participation_pct                                           float64
lea_sat_participation_pct                                       float64
ap_participation_pct                                            float64
lea_ap_participation_pct                                        float64
ap_pct_3_or_above                                               float64
lea_ap_pct_3_or_above                                           float64
lea_ib_pct_4_or_above                                           float64
total_specialized_courses                                       float64
cte_courses                                                     float64
univ_college_courses                                            float64
lea_ap_ib_courses                                               float64
lea_univ_college_courses                                        float64
ALL_All Students (Total or Subtotal_ENROLL_sch_pct              float64
ECODIS_Economically Disadvantaged_ENROLL_sch_pct                float64
MB_Black_ENROLL_sch_pct                                         float64
MHL_Hispanic_ENROLL_sch_pct                                     float64
MW_White_ENROLL_sch_pct                                         float64
avg_daily_attend_pct                                            float64
crime_per_c_num                                                 float64
short_susp_per_c_num                                            float64
long_susp_per_c_num                                             float64
expelled_per_c_num                                              float64
stud_internet_comp_num                                          float64
lea_avg_daily_attend_pct                                        float64
lea_crime_per_c_num                                             float64
lea_short_susp_per_c_num                                        float64
lea_long_susp_per_c_num                                         float64
lea_expelled_per_c_num                                          float64
lea_stud_internet_comp_num                                      float64
st_avg_daily_attend_pct                                         float64
st_crime_per_c_num                                              float64
st_short_susp_per_c_num                                         float64
st_long_susp_per_c_num                                          float64
st_expelled_per_c_num                                           float64
digital_media_pct                                               float64
avg_age_media_collection                                        float64
books_per_student                                               float64
lea_books_per_student                                           float64
wap_num                                                         float64
wap_per_classroom                                               float64
lea_wap_num                                                     float64
lea_wap_per_classroom                                           float64
flicensed_teach_pct                                             float64
tchyrs_0thru3_pct                                               float64
tchyrs_4thru10_pct                                              float64
tchyrs_11plus_pct                                               float64
nbpts_num                                                       float64
advance_dgr_pct                                                 float64
_1yr_tchr_trnovr_pct                                            float64
emer_prov_teach_pct                                             float64
lateral_teach_pct                                               float64
lea_flicensed_teach_pct                                         float64
lea_tchyrs_0thru3_pct                                           float64
lea_tchyrs_4thru10_pct                                          float64
lea_tchyrs_11plus_pct                                           float64
lea_nbpts_num                                                   float64
lea_advance_dgr_pct                                             float64
lea_1yr_tchr_trnovr_pct                                         float64
lea_emer_prov_teach_pct                                         float64
st_flicensed_teach_pct                                          float64
st_tchyrs_0thru3_pct                                            float64
st_nbpts_num                                                    float64
st_1yr_tchr_trnovr_pct                                          float64
st_emer_prov_teach_pct                                          float64
0-3 Years_LEA_Exp_Pct_Prin                                      float64
10+ Years_LEA_Exp_Pct_Prin                                      float64
4-10 Years_LEA_Exp_Pct_Prin                                     float64
Accomplished_TCHR_Standard 1_Pct                                float64
Accomplished_TCHR_Standard 2_Pct                                float64
Accomplished_TCHR_Standard 3_Pct                                float64
Accomplished_TCHR_Standard 4_Pct                                float64
Accomplished_TCHR_Standard 5_Pct                                float64
Developing_TCHR_Standard 1_Pct                                  float64
Developing_TCHR_Standard 2_Pct                                  float64
Developing_TCHR_Standard 3_Pct                                  float64
Developing_TCHR_Standard 4_Pct                                  float64
Developing_TCHR_Standard 5_Pct                                  float64
Distinguished_TCHR_Standard 1_Pct                               float64
Distinguished_TCHR_Standard 2_Pct                               float64
Distinguished_TCHR_Standard 3_Pct                               float64
Distinguished_TCHR_Standard 4_Pct                               float64
Distinguished_TCHR_Standard 5_Pct                               float64
Does Not Meet Expected Growth_TCHR_Student Growth_Pct           float64
Exceeds Expected Growth_TCHR_Student Growth_Pct                 float64
Meets Expected Growth_TCHR_Student Growth_Pct                   float64
Not Demostrated_TCHR_Standard 1_Pct                             float64
Not Demostrated_TCHR_Standard 2_Pct                             float64
Not Demostrated_TCHR_Standard 4_Pct                             float64
Proficient_TCHR_Standard 1_Pct                                  float64
Proficient_TCHR_Standard 2_Pct                                  float64
Proficient_TCHR_Standard 3_Pct                                  float64
Proficient_TCHR_Standard 4_Pct                                  float64
Proficient_TCHR_Standard 5_Pct                                  float64
AsianFemalePct                                                  float64
AsianMalePct                                                    float64
BlackFemalePct                                                  float64
BlackMalePct                                                    float64
HispanicFemalePct                                               float64
HispanicMalePct                                                 float64
IndianFemalePct                                                 float64
MinorityFemalePct                                               float64
MinorityMalePct                                                 float64
PacificIslandFemalePct                                          float64
PacificIslandMalePct                                            float64
PacificIslandPct                                                float64
TwoOrMoreFemalePct                                              float64
TwoOrMoreMalePct                                                float64
TwoOrMorePct                                                    float64
Gr_6_Pct_Prof                                                   float64
Gr_9_Pct_Prof                                                   float64
pct_eds                                                         float64
AAVC_Concentrator_Ct                                            float64
AGNR_Concentrator_Ct                                            float64
ARCH_Concentrator_Ct                                            float64
BMA_Concentrator_Ct                                             float64
FINA_Concentrator_Ct                                            float64
HLTH_Concentrator_Ct                                            float64
HOSP_Concentrator_Ct                                            float64
HUMA_Concentrator_Ct                                            float64
INFO_Concentrator_Ct                                            float64
LAW_Concentrator_Ct                                             float64
MANU_Concentrator_Ct                                            float64
MRKT_Concentrator_Ct                                            float64
STEM_Concentrator_Ct                                            float64
TRAN_Concentrator_Ct                                            float64
Number_Industry_Recognized_Crede                                float64
LPS_14                                                          int64
LPS_15                                                          int64
LPS_16                                                          int64
LPS_17                                                          int64
RLPS                                                            int64
category_cd_E                                                   uint8
category_cd_H                                                   uint8
category_cd_I                                                   uint8
category_cd_M                                                   uint8
calendar_type_txt_Hospital School                               uint8
calendar_type_txt_Magnet School, Traditional Calendar           uint8
calendar_type_txt_Magnet School, Year-Round Calendar            uint8
calendar_type_txt_Regular School, Traditional Calendar          uint8
calendar_type_txt_Regular School, Year-Round Calendar           uint8
calendar_type_txt_Special Education, Traditional Calendar       uint8
calendar_type_txt_Vocational Education, Traditional Calendar    uint8
school_type_txt_Magnet School                                   uint8
school_type_txt_Regular School                                  uint8
calendar_only_txt_Year-Round Calendar                           uint8
esea_status_Esea_Pass                                           uint8
esea_status_Non_Esea                                            uint8
SBE District_Northeast                                          uint8
SBE District_Northwest                                          uint8
SBE District_Piedmont-Triad                                     uint8
SBE District_Sandhills                                          uint8
SBE District_Southeast                                          uint8
SBE District_Southwest                                          uint8
SBE District_Western                                            uint8
SPG Grade_A+NG                                                  uint8
SPG Grade_B                                                     uint8
SPG Grade_C                                                     uint8
SPG Grade_D                                                     uint8
SPG Grade_F                                                     uint8
Reading SPG Grade_B                                             uint8
Reading SPG Grade_C                                             uint8
Reading SPG Grade_D                                             uint8
Reading SPG Grade_F                                             uint8
Math SPG Grade_B                                                uint8
Math SPG Grade_C                                                uint8
Math SPG Grade_D                                                uint8
Math SPG Grade_F                                                uint8
EVAAS Growth Status_Met                                         uint8
EVAAS Growth Status_NotMet                                      uint8
State Gap Compared_Y                                            uint8
Byod_Yes                                                        uint8
_1_to_1_access_Yes                                              uint8
SRC_devices_sent_home_Yes                                       uint8
unit_code                                                       object
dtypes: float64(167), int64(12), object(1), uint8(42)
memory usage: 3.5+ MB